#include "smgf.h"
#include "api_lua.h"

// physfs refuses paths that contain a "." component ("./foo.lua" gives a
// PHYSFS_ERR_BAD_FILENAME error), and a leading "/" is redundant since
// everything is mounted on "/": normalise a path template before using it.
static const char* physfs_path(const char* path) {
  while (*path == '/' || (path[0] == '.' && path[1] == '/')) {
    path += (*path == '/') ? 1 : 2;
  }
  return path;
}

// physfs equivalent of Lua's "readable": true only if the file exists *and* is
// a regular file (PHYSFS_exists is also true for directories).
static bool physfs_is_file(const char* filename) {
  PHYSFS_Stat stat;
  if (*filename == '\0' || PHYSFS_stat(filename, &stat) == 0) {
    return false;
  }
  return stat.filetype == PHYSFS_FILETYPE_REGULAR;
}

// searches for a module name in a search path (usually package.path), through
// physfs. On success, pushes the file name onto the Lua stack and returns it.
// On failure, pushes an error message listing every file name tried (like Lua
// does) and returns NULL.
const char* searchpath(
    lua_State* L, const char* name, const char* path, const char* sep,
    const char* dirsep) {
  // we replace Lua's "." module separator with a slash (for physfs),
  // and create a new path variable with "?" characters replaced by module name
  const char* name_withdirsep = luaL_gsub(L, name, sep, dirsep);
  const char* path_withmodname =
      luaL_gsub(L, path, LUA_PATH_MARK, name_withdirsep);
  lua_remove(L, -2); // remove the string generated by the first gsub

  // we iterate over all templates (which are separated by a ";")
  const char* path_curpos = path_withmodname;

  while (*path_curpos != '\0') {
    const char* separator_pos = SDL_strchr(path_curpos, *LUA_PATH_SEP);

    // if there's no more separator in string, we set the separator to end
    // of string
    if (separator_pos == NULL) {
      separator_pos = path_curpos + SDL_strlen(path_curpos);
    }

    lua_pushlstring(L, path_curpos, (size_t) (separator_pos - path_curpos));
    const char* filename = physfs_path(lua_tostring(L, -1));

    if (physfs_is_file(filename)) {
      lua_remove(L, -2); // remove path_withmodname, keep the file name
      return filename;
    }

    lua_pop(L, 1);
    path_curpos = (*separator_pos == '\0') ? separator_pos : separator_pos + 1;
  }

  // not found: build the "no file 'a'\n\tno file 'b'" message Lua would give
  luaL_Buffer b;
  luaL_buffinit(L, &b);
  luaL_addstring(&b, "no file '");
  luaL_addgsub(&b, path_withmodname, LUA_PATH_SEP, "'\n\tno file '");
  luaL_addstring(&b, "'");
  luaL_pushresult(&b);
  lua_remove(L, -2); // remove the string generated by the second gsub
  return NULL;
}

#define SMGF_LOADBUF_SIZE 4096

// state of a chunk being streamed from physfs into lua_load
typedef struct smgf_loadf {
  PHYSFS_File* file;
  bool read_error;
  char buff[SMGF_LOADBUF_SIZE];
} smgf_loadf;

// lua_Reader over a physfs file (equivalent of "getF" in lauxlib.c)
static const char* smgf_getf(lua_State* L, void* ud, size_t* size) {
  smgf_loadf* const lf = (smgf_loadf*) ud;
  (void) L;

  PHYSFS_sint64 nb_read =
      PHYSFS_readBytes(lf->file, lf->buff, SMGF_LOADBUF_SIZE);
  if (nb_read < 0) {
    lf->read_error = true;
  }
  if (nb_read <= 0) { // error or end of file
    *size = 0;
    return NULL;
  }

  *size = (size_t) nb_read;
  return lf->buff;
}

// custom smgf package.searcher that tries to load modules through physfs
// (equivalent of "searcher_Lua" in loadlib.c). "package" is upvalue 1.
int l_smgf_searcher(lua_State* L) {
  const char* mod_name = luaL_checkstring(L, 1);

  if (lua_getfield(L, lua_upvalueindex(1), "path") != LUA_TSTRING) {
    return luaL_error(L, "'package.path' must be a string");
  }
  const char* packagepath = lua_tostring(L, -1);

  // finding a file matching the module name
  const char* file_name = searchpath(L, mod_name, packagepath, ".", "/");

  if (file_name == NULL) {
    return 1; // searchpath pushed the "no file '...'" message for require
  }

  // loading file
  smgf_loadf lf;
  lf.read_error = false;
  lf.file = PHYSFS_openRead(file_name);

  if (lf.file == NULL) {
    return luaL_error(
        L, "error loading module '%s' from file '%s':\n\t%s", mod_name,
        file_name, PHYSFS_getErrorByCode(PHYSFS_getLastErrorCode()));
  }

  // the "@" prefix tells Lua the chunk comes from a file, so that errors read
  // "mymodule.lua:12: ..." instead of "[string \"mymodule.lua\"]:12: ..."
  lua_pushfstring(L, "@%s", file_name);
  int status = lua_load(L, smgf_getf, &lf, lua_tostring(L, -1), NULL);
  PHYSFS_close(lf.file);

  if (lf.read_error) {
    return luaL_error(
        L, "error loading module '%s' from file '%s':\n\tread error", mod_name,
        file_name);
  }

  if (status != LUA_OK) {
    return luaL_error(
        L, "error loading module '%s' from file '%s':\n\t%s", mod_name,
        file_name, lua_tostring(L, -1));
  }

  lua_pushstring(L, file_name); // will be 2nd argument to module

  return 2;
}

// initialises a Lua state for smgf use
void lua_api_init(smgf* const c) {
  // store a pointer to smgf struct in Lua registry
  lua_pushstring(c->L, SMGF_PTRNAME);
  lua_pushlightuserdata(c->L, (void*) c);
  lua_settable(c->L, LUA_REGISTRYINDEX);

  // open standard libs
  luaL_openlibs(c->L);

  // remove almost entire io module, except: io.flush, io.write, io.stderr,
  // io.stdout
  lua_getglobal(c->L, "io");
  lua_pushnil(c->L);
  lua_setfield(c->L, -2, "close");
  lua_pushnil(c->L);
  lua_setfield(c->L, -2, "input");
  lua_pushnil(c->L);
  lua_setfield(c->L, -2, "lines");
  lua_pushnil(c->L);
  lua_setfield(c->L, -2, "open");
  lua_pushnil(c->L);
  lua_setfield(c->L, -2, "output");
  lua_pushnil(c->L);
  lua_setfield(c->L, -2, "popen");
  lua_pushnil(c->L);
  lua_setfield(c->L, -2, "read");
  lua_pushnil(c->L);
  lua_setfield(c->L, -2, "stdin");
  lua_pushnil(c->L);
  lua_setfield(c->L, -2, "tmpfile");
  lua_pushnil(c->L);
  lua_setfield(c->L, -2, "type");
  lua_pop(c->L, 1);

  // remove some functions from os module
  lua_getglobal(c->L, "os");
  lua_pushnil(c->L);
  lua_setfield(c->L, -2, "execute");
  lua_pushnil(c->L);
  lua_setfield(c->L, -2, "exit");
  lua_pushnil(c->L);
  lua_setfield(c->L, -2, "getenv");
  lua_pushnil(c->L);
  lua_setfield(c->L, -2, "remove");
  lua_pushnil(c->L);
  lua_setfield(c->L, -2, "rename");
  lua_pushnil(c->L);
  lua_setfield(c->L, -2, "setlocale");
  lua_pushnil(c->L);
  lua_setfield(c->L, -2, "tmpname");
  lua_pop(c->L, 1);

  // remove dofile & loadfile
  lua_pushnil(c->L);
  lua_setglobal(c->L, "dofile");
  lua_pushnil(c->L);
  lua_setglobal(c->L, "loadfile");

  // set package.path + cpath
  lua_getglobal(c->L, "package");
  lua_pushstring(c->L, "./?.lua;./?/init.lua");
  lua_setfield(c->L, -2, "path");
  lua_pushstring(c->L, "");
  lua_setfield(c->L, -2, "cpath");
  lua_pop(c->L, 1);

  // we have to setup a custom package loader into package.searchers
  // so that modules are loaded through physfs
  // We overwrite package.searcher n°2 (the one using package.path). See:
  // https://www.lua.org/manual/5.5/manual.html#pdf-package.searchers
  lua_getglobal(c->L, "package");
  lua_getfield(c->L, -1, "searchers");
  // like Lua's own searchers, ours reads "package.path" from an upvalue
  // rather than from the global table, so that a game cannot break "require"
  // by overwriting the "package" global
  lua_pushvalue(c->L, -2);
  lua_pushcclosure(c->L, l_smgf_searcher, 1);
  lua_rawseti(c->L, -2, 2);
  // removing 3st & 4th package searchers that allow module loading
  // from C libraries:
  lua_pushnil(c->L);
  lua_rawseti(c->L, -2, 3);
  lua_pushnil(c->L);
  lua_rawseti(c->L, -2, 4);
  lua_pop(c->L, 1);
  // removing package.searchpath & package.loadlib
  lua_pushnil(c->L);
  lua_setfield(c->L, -2, "searchpath");
  lua_pushnil(c->L);
  lua_setfield(c->L, -2, "loadlib");
  lua_pop(c->L, 1);

  // add smgf table
  lua_newtable(c->L); // create smgf table

  // add modules to smgf table
  init_audio(c->L);
  init_graphics(c->L);
  init_input(c->L);
  init_io(c->L);
  init_system(c->L);

  // set smgf table global
  lua_setglobal(c->L, "smgf");
}

double lua_get_memory_kb(lua_State* L) {
  int count_k = lua_gc(L, LUA_GCCOUNT, 0);
  int count_b = lua_gc(L, LUA_GCCOUNTB, 0);
  return count_k + (count_b / 1024.0);
}
